import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { load } from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const i18nDir = join(root, "src", "i18n");
const outFile = join(i18nDir, "messages.generated.ts");

const files = readdirSync(i18nDir)
  .filter((f) => /^messages_[a-z]{2}\.yaml$/.test(f))
  .sort();

if (files.length === 0) {
  console.error("No messages_*.yaml found in", i18nDir);
  process.exit(1);
}

const locales = {};
const keySets = {};

for (const file of files) {
  const locale = file.match(/^messages_([a-z]{2})\.yaml$/)[1];
  const raw = readFileSync(join(i18nDir, file), "utf8");
  const data = load(raw);
  if (!data || typeof data !== "object") {
    throw new Error(`${file}: YAML root must be a mapping`);
  }
  locales[locale] = data;
  keySets[locale] = collectKeys(data);
}

// Ensure all locales share the exact same key tree so t() can never point
// to a missing key when switching languages.
const reference = Object.keys(keySets)[0];
for (const [locale, keys] of Object.entries(keySets)) {
  const missing = keySets[reference].filter((k) => !keys.includes(k));
  const extra = keys.filter((k) => !keySets[reference].includes(k));
  if (missing.length || extra.length) {
    console.error(
      `[i18n] Locale "${locale}" key mismatch vs "${reference}"\n` +
        `  missing: ${missing.join(", ") || "—"}\n  extra:   ${extra.join(", ") || "—"}`
    );
    process.exit(1);
  }
}

function collectKeys(node, prefix = "") {
  if (typeof node !== "object" || node === null) return [];
  if (Array.isArray(node) || typeof node !== "object") {
    return typeof node === "string" ? [prefix] : [];
  }
  const keys = [];
  for (const [k, v] of Object.entries(node)) {
    const path = prefix ? `${prefix}.${k}` : k;
    if (typeof v === "string") keys.push(path);
    else keys.push(...collectKeys(v, path));
  }
  return keys;
}

function tsLiteral(value) {
  return JSON.stringify(value);
}

function renderObject(node, indent = 0) {
  const pad = "  ".repeat(indent);
  const padInner = "  ".repeat(indent + 1);
  const lines = [];
  for (const [k, v] of Object.entries(node)) {
    if (typeof v === "string") {
      lines.push(`${padInner}${JSON.stringify(k)}: ${tsLiteral(v)},`);
    } else {
      lines.push(`${padInner}${JSON.stringify(k)}: ${renderObject(v, indent + 1)},`);
    }
  }
  return `{\n${lines.join("\n")}\n${pad}}`;
}

const chunks = [];
chunks.push("/* eslint-disable */");
chunks.push("// ⚠️ AUTO-GENERATED by scripts/generate-i18n.mjs — do not edit by hand.");
chunks.push("// Run `npm run i18n:gen` to regenerate.");
chunks.push("");
chunks.push("export type Locale = " + Object.keys(locales).map((l) => `"${l}"`).join(" | ") + ";");
chunks.push("");
for (const [locale, data] of Object.entries(locales)) {
  chunks.push(`const ${locale} = ${renderObject(data)} as const;`);
  chunks.push("");
}
chunks.push(
  "export const messages: Record<Locale, Record<string, unknown>> = {\n" +
    Object.keys(locales).map((l) => `  ${l},`).join("\n") +
    "\n} as const;"
);
chunks.push("");
chunks.push(`export const defaultLocale: Locale = "${Object.keys(locales)[0]}";`);
chunks.push("");

mkdirSync(i18nDir, { recursive: true });
writeFileSync(outFile, chunks.join("\n"), "utf8");

console.log(`[i18n] Generated ${Object.keys(locales).length} locale(s) -> ${outFile.replace(root + "\\", "")}`);